# arm64-toolchain.cmake
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ARM64)
set(CMAKE_VS_PLATFORM_NAME ARM64)

# 工具链路径
set(COMPILER_PATH "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.42.34433/bin/Hostx64/arm64")
set(CMAKE_C_COMPILER "${COMPILER_PATH}/cl.exe")
set(CMAKE_CXX_COMPILER "${COMPILER_PATH}/cl.exe")
set(CMAKE_RC_COMPILER "${COMPILER_PATH}/rc.exe")

# 禁用编译器检查
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Windows SDK 路径
set(CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION 10.0)
set(CMAKE_VS_WINDOWS_TARGET_PLATFORM "arm64")