/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_ASSETREFERENCE_PB_H_INCLUDED
#define PB_ASSETREFERENCE_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* ==================== 资产引用消息 ====================
 用于在编辑器目录中记录原始文件与.gnx目录中资产文件的映射关系 */
typedef struct _AssetReferenceMessage {
    /* 资产类型（可选，用于快速识别） */
    AssetType assetType;
    /* 资产哈希值（对应.gnx目录中的文件名） */
    uint64_t hash;
    /* 原始文件名（例如：my_albedo.png） */
    pb_callback_t originalFileName;
    /* 导入时间 */
    pb_callback_t importTime;
    /* 引擎版本 */
    pb_callback_t engineVersion;
    /* 原始文件路径（相对路径） */
    pb_callback_t originalPath;
} AssetReferenceMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AssetReferenceMessage_init_default       {_AssetType_MIN, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define AssetReferenceMessage_init_zero          {_AssetType_MIN, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define AssetReferenceMessage_assetType_tag      1
#define AssetReferenceMessage_hash_tag           2
#define AssetReferenceMessage_originalFileName_tag 3
#define AssetReferenceMessage_importTime_tag     4
#define AssetReferenceMessage_engineVersion_tag  5
#define AssetReferenceMessage_originalPath_tag   6

/* Struct field encoding specification for nanopb */
#define AssetReferenceMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    assetType,         1) \
X(a, STATIC,   SINGULAR, UINT64,   hash,              2) \
X(a, CALLBACK, SINGULAR, STRING,   originalFileName,   3) \
X(a, CALLBACK, SINGULAR, STRING,   importTime,        4) \
X(a, CALLBACK, SINGULAR, STRING,   engineVersion,     5) \
X(a, CALLBACK, SINGULAR, STRING,   originalPath,      6)
#define AssetReferenceMessage_CALLBACK pb_default_field_callback
#define AssetReferenceMessage_DEFAULT NULL

extern const pb_msgdesc_t AssetReferenceMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AssetReferenceMessage_fields &AssetReferenceMessage_msg

/* Maximum encoded size of messages (where known) */
/* AssetReferenceMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
