/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHADERMESSAGE_PB_H_INCLUDED
#define PB_SHADERMESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _GnxShaderStage {
    GnxShaderStage_GnxShaderStage_Vertex = 0,
    GnxShaderStage_GnxShaderStage_Fragment = 1,
    GnxShaderStage_GnxShaderStage_Compute = 2,
    GnxShaderStage_GnxShaderStage_Task = 3,
    GnxShaderStage_GnxShaderStage_Mesh = 4
} GnxShaderStage;

typedef enum _GnxShaderFormat {
    GnxShaderFormat_GnxShaderFormat_SPIRV = 0,
    GnxShaderFormat_GnxShaderFormat_MSL_iOS = 1,
    GnxShaderFormat_GnxShaderFormat_MSL_macOS = 2,
    GnxShaderFormat_GnxShaderFormat_DXIL = 3,
    GnxShaderFormat_GnxShaderFormat_GLSL = 4
} GnxShaderFormat;

/* Struct definitions */
typedef struct _UniformMemberMessage {
    pb_callback_t name;
    uint32_t offset;
    uint32_t size;
    VertexDataFormat format;
} UniformMemberMessage;

typedef struct _UniformBufferLayoutMessage {
    pb_callback_t name;
    uint32_t dataSize;
    uint32_t set;
    uint32_t binding;
    pb_callback_t members;
} UniformBufferLayoutMessage;

typedef struct _PushConstantMessage {
    pb_callback_t name;
    uint32_t size;
    uint32_t set;
    uint32_t binding;
} PushConstantMessage;

typedef struct _ShaderResourceMessage {
    pb_callback_t name;
    uint32_t set;
    uint32_t binding;
    uint32_t msl_texture;
    uint32_t msl_sampler;
} ShaderResourceMessage;

typedef struct _VertexInputMessage {
    pb_callback_t semantic;
    uint32_t location;
    VertexDataFormat format;
    uint32_t offset;
    uint32_t stride;
} VertexInputMessage;

typedef struct _ShaderMessage {
    GnxShaderStage shaderStage;
    GnxShaderFormat shaderFormat;
    pb_callback_t entryPoint;
    uint64_t sourceHash;
    pb_callback_t compiledShader;
    pb_callback_t uniformBuffers;
    pb_callback_t pushConstants;
    pb_callback_t resources;
    pb_callback_t vertexInputs;
    uint32_t threadgroupSizeX;
    uint32_t threadgroupSizeY;
    uint32_t threadgroupSizeZ;
    uint32_t vertexStride;
} ShaderMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _GnxShaderStage_MIN GnxShaderStage_GnxShaderStage_Vertex
#define _GnxShaderStage_MAX GnxShaderStage_GnxShaderStage_Mesh
#define _GnxShaderStage_ARRAYSIZE ((GnxShaderStage)(GnxShaderStage_GnxShaderStage_Mesh+1))

#define _GnxShaderFormat_MIN GnxShaderFormat_GnxShaderFormat_SPIRV
#define _GnxShaderFormat_MAX GnxShaderFormat_GnxShaderFormat_GLSL
#define _GnxShaderFormat_ARRAYSIZE ((GnxShaderFormat)(GnxShaderFormat_GnxShaderFormat_GLSL+1))

#define UniformMemberMessage_format_ENUMTYPE VertexDataFormat




#define VertexInputMessage_format_ENUMTYPE VertexDataFormat

#define ShaderMessage_shaderStage_ENUMTYPE GnxShaderStage
#define ShaderMessage_shaderFormat_ENUMTYPE GnxShaderFormat


/* Initializer values for message structs */
#define UniformMemberMessage_init_default        {{{NULL}, NULL}, 0, 0, _VertexDataFormat_MIN}
#define UniformBufferLayoutMessage_init_default  {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define PushConstantMessage_init_default         {{{NULL}, NULL}, 0, 0, 0}
#define ShaderResourceMessage_init_default       {{{NULL}, NULL}, 0, 0, 0, 0}
#define VertexInputMessage_init_default          {{{NULL}, NULL}, 0, _VertexDataFormat_MIN, 0, 0}
#define ShaderMessage_init_default               {_GnxShaderStage_MIN, _GnxShaderFormat_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}
#define UniformMemberMessage_init_zero           {{{NULL}, NULL}, 0, 0, _VertexDataFormat_MIN}
#define UniformBufferLayoutMessage_init_zero     {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define PushConstantMessage_init_zero            {{{NULL}, NULL}, 0, 0, 0}
#define ShaderResourceMessage_init_zero          {{{NULL}, NULL}, 0, 0, 0, 0}
#define VertexInputMessage_init_zero             {{{NULL}, NULL}, 0, _VertexDataFormat_MIN, 0, 0}
#define ShaderMessage_init_zero                  {_GnxShaderStage_MIN, _GnxShaderFormat_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define UniformMemberMessage_name_tag            1
#define UniformMemberMessage_offset_tag          2
#define UniformMemberMessage_size_tag            3
#define UniformMemberMessage_format_tag          4
#define UniformBufferLayoutMessage_name_tag      1
#define UniformBufferLayoutMessage_dataSize_tag  2
#define UniformBufferLayoutMessage_set_tag       3
#define UniformBufferLayoutMessage_binding_tag   4
#define UniformBufferLayoutMessage_members_tag   5
#define PushConstantMessage_name_tag             1
#define PushConstantMessage_size_tag             2
#define PushConstantMessage_set_tag              3
#define PushConstantMessage_binding_tag          4
#define ShaderResourceMessage_name_tag           1
#define ShaderResourceMessage_set_tag            2
#define ShaderResourceMessage_binding_tag        3
#define ShaderResourceMessage_msl_texture_tag    4
#define ShaderResourceMessage_msl_sampler_tag    5
#define VertexInputMessage_semantic_tag          1
#define VertexInputMessage_location_tag          2
#define VertexInputMessage_format_tag            3
#define VertexInputMessage_offset_tag            4
#define VertexInputMessage_stride_tag            5
#define ShaderMessage_shaderStage_tag            1
#define ShaderMessage_shaderFormat_tag           2
#define ShaderMessage_entryPoint_tag             3
#define ShaderMessage_sourceHash_tag             4
#define ShaderMessage_compiledShader_tag         5
#define ShaderMessage_uniformBuffers_tag         6
#define ShaderMessage_pushConstants_tag          7
#define ShaderMessage_resources_tag              8
#define ShaderMessage_vertexInputs_tag           9
#define ShaderMessage_threadgroupSizeX_tag       10
#define ShaderMessage_threadgroupSizeY_tag       11
#define ShaderMessage_threadgroupSizeZ_tag       12
#define ShaderMessage_vertexStride_tag           13

/* Struct field encoding specification for nanopb */
#define UniformMemberMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            2) \
X(a, STATIC,   SINGULAR, UINT32,   size,              3) \
X(a, STATIC,   SINGULAR, UENUM,    format,            4)
#define UniformMemberMessage_CALLBACK pb_default_field_callback
#define UniformMemberMessage_DEFAULT NULL

#define UniformBufferLayoutMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   dataSize,          2) \
X(a, STATIC,   SINGULAR, UINT32,   set,               3) \
X(a, STATIC,   SINGULAR, UINT32,   binding,           4) \
X(a, CALLBACK, REPEATED, MESSAGE,  members,           5)
#define UniformBufferLayoutMessage_CALLBACK pb_default_field_callback
#define UniformBufferLayoutMessage_DEFAULT NULL
#define UniformBufferLayoutMessage_members_MSGTYPE UniformMemberMessage

#define PushConstantMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   size,              2) \
X(a, STATIC,   SINGULAR, UINT32,   set,               3) \
X(a, STATIC,   SINGULAR, UINT32,   binding,           4)
#define PushConstantMessage_CALLBACK pb_default_field_callback
#define PushConstantMessage_DEFAULT NULL

#define ShaderResourceMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   set,               2) \
X(a, STATIC,   SINGULAR, UINT32,   binding,           3) \
X(a, STATIC,   SINGULAR, UINT32,   msl_texture,       4) \
X(a, STATIC,   SINGULAR, UINT32,   msl_sampler,       5)
#define ShaderResourceMessage_CALLBACK pb_default_field_callback
#define ShaderResourceMessage_DEFAULT NULL

#define VertexInputMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   semantic,          1) \
X(a, STATIC,   SINGULAR, UINT32,   location,          2) \
X(a, STATIC,   SINGULAR, UENUM,    format,            3) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            4) \
X(a, STATIC,   SINGULAR, UINT32,   stride,            5)
#define VertexInputMessage_CALLBACK pb_default_field_callback
#define VertexInputMessage_DEFAULT NULL

#define ShaderMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    shaderStage,       1) \
X(a, STATIC,   SINGULAR, UENUM,    shaderFormat,      2) \
X(a, CALLBACK, SINGULAR, STRING,   entryPoint,        3) \
X(a, STATIC,   SINGULAR, UINT64,   sourceHash,        4) \
X(a, CALLBACK, SINGULAR, BYTES,    compiledShader,    5) \
X(a, CALLBACK, REPEATED, MESSAGE,  uniformBuffers,    6) \
X(a, CALLBACK, REPEATED, MESSAGE,  pushConstants,     7) \
X(a, CALLBACK, REPEATED, MESSAGE,  resources,         8) \
X(a, CALLBACK, REPEATED, MESSAGE,  vertexInputs,      9) \
X(a, STATIC,   SINGULAR, UINT32,   threadgroupSizeX,  10) \
X(a, STATIC,   SINGULAR, UINT32,   threadgroupSizeY,  11) \
X(a, STATIC,   SINGULAR, UINT32,   threadgroupSizeZ,  12) \
X(a, STATIC,   SINGULAR, UINT32,   vertexStride,     13)
#define ShaderMessage_CALLBACK pb_default_field_callback
#define ShaderMessage_DEFAULT NULL
#define ShaderMessage_uniformBuffers_MSGTYPE UniformBufferLayoutMessage
#define ShaderMessage_pushConstants_MSGTYPE PushConstantMessage
#define ShaderMessage_resources_MSGTYPE ShaderResourceMessage
#define ShaderMessage_vertexInputs_MSGTYPE VertexInputMessage

extern const pb_msgdesc_t UniformMemberMessage_msg;
extern const pb_msgdesc_t UniformBufferLayoutMessage_msg;
extern const pb_msgdesc_t PushConstantMessage_msg;
extern const pb_msgdesc_t ShaderResourceMessage_msg;
extern const pb_msgdesc_t VertexInputMessage_msg;
extern const pb_msgdesc_t ShaderMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UniformMemberMessage_fields &UniformMemberMessage_msg
#define UniformBufferLayoutMessage_fields &UniformBufferLayoutMessage_msg
#define PushConstantMessage_fields &PushConstantMessage_msg
#define ShaderResourceMessage_fields &ShaderResourceMessage_msg
#define VertexInputMessage_fields &VertexInputMessage_msg
#define ShaderMessage_fields &ShaderMessage_msg

/* Maximum encoded size of messages (where known) */
/* UniformMemberMessage_size depends on runtime parameters */
/* UniformBufferLayoutMessage_size depends on runtime parameters */
/* PushConstantMessage_size depends on runtime parameters */
/* ShaderResourceMessage_size depends on runtime parameters */
/* VertexInputMessage_size depends on runtime parameters */
/* ShaderMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
