/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHADERMESSAGE_PB_H_INCLUDED
#define PB_SHADERMESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ==================== Shader 阶段 ==================== */
typedef enum _GnxShaderStage {
    GnxShaderStage_GnxShaderStage_Vertex = 0,
    GnxShaderStage_GnxShaderStage_Fragment = 1,
    GnxShaderStage_GnxShaderStage_Compute = 2,
    GnxShaderStage_GnxShaderStage_Task = 3,
    GnxShaderStage_GnxShaderStage_Mesh = 4
} GnxShaderStage;

/* ==================== Shader 运行时格式 ====================
 编译后可直接在对应平台加载的 shader 数据格式 */
typedef enum _GnxShaderFormat {
    GnxShaderFormat_GnxShaderFormat_SPIRV = 0, /* SPIR-V 二进制（Android Vulkan / macOS MoltenVK） */
    GnxShaderFormat_GnxShaderFormat_MSL_iOS = 1, /* Metal Shading Language for iOS（Apple GPU Family） */
    GnxShaderFormat_GnxShaderFormat_MSL_macOS = 2, /* Metal Shading Language for macOS（Mac GPU Family） */
    GnxShaderFormat_GnxShaderFormat_DXIL = 3, /* DXIL 字节码（Windows D3D12） */
    GnxShaderFormat_GnxShaderFormat_GLSL = 4 /* GLSL 源码（OpenGL ES / 兼容层） */
} GnxShaderFormat;

/* Struct definitions */
/* ==================== Uniform Buffer 成员 ==================== */
typedef struct _UniformMemberMessage {
    pb_callback_t name; /* 成员名 */
    uint32_t offset; /* buffer 内字节偏移 */
    uint32_t size; /* 成员大小（字节） */
    VertexDataFormat format; /* 数据格式（复用 Common.proto） */
} UniformMemberMessage;

/* ==================== Uniform Buffer 布局 ==================== */
typedef struct _UniformBufferLayoutMessage {
    pb_callback_t name; /* cbuffer 名 */
    uint32_t dataSize; /* buffer 总大小（字节） */
    uint32_t set; /* descriptor set */
    uint32_t binding; /* descriptor binding */
    pb_callback_t members;
} UniformBufferLayoutMessage;

/* ==================== Push Constant ==================== */
typedef struct _PushConstantMessage {
    pb_callback_t name; /* 原始 cbuffer 名 */
    uint32_t size; /* padded size（字节） */
    uint32_t set; /* 原始 descriptor set（反向查表） */
    uint32_t binding; /* 原始 descriptor binding（反向查表） */
} PushConstantMessage;

/* ==================== 采样器/纹理反射资源 ==================== */
typedef struct _ShaderResourceMessage {
    pb_callback_t name;
    uint32_t set;
    uint32_t binding;
    uint32_t msl_texture; /* Metal 重映射后的纹理槽位（MSL 专用） */
    uint32_t msl_sampler; /* Metal 重映射后的采样器槽位（MSL 专用） */
} ShaderResourceMessage;

/* ==================== 顶点输入属性 ==================== */
typedef struct _VertexInputMessage {
    pb_callback_t semantic; /* 语义名（"POSITION" / "NORMAL" / "TEXCOORD"） */
    uint32_t location; /* attribute location */
    VertexDataFormat format; /* 数据格式 */
    uint32_t offset; /* vertex stride 内字节偏移 */
} VertexInputMessage;

/* ==================== 编译后的 Shader ====================
 一个 ShaderMessage 对应一个 stage 在当前平台的一份编译结果 */
typedef struct _ShaderMessage {
    /* ====== 标识 ====== */
    GnxShaderStage shaderStage; /* VS / PS / CS / TS / MS */
    GnxShaderFormat shaderFormat; /* SPIRV / MSL_iOS / MSL_macOS / DXIL / GLSL */
    pb_callback_t entryPoint; /* 入口函数名（Metal 需要） */
    uint64_t sourceHash; /* HLSL 源码 hash（增量编译 / 版本追踪） */
    /* ====== 编译后的 shader 数据 ====== */
    pb_callback_t compiledShader; /* 格式由 shaderFormat 决定 */
    /* ====== 反射元数据 ====== */
    pb_callback_t uniformBuffers;
    pb_callback_t pushConstants;
    pb_callback_t resources; /* sampled images + separate samplers */
    pb_callback_t vertexInputs;
    /* ====== Threadgroup 大小（TS / MS / CS 有效） ====== */
    uint32_t threadgroupSizeX;
    uint32_t threadgroupSizeY;
    uint32_t threadgroupSizeZ;
    /* ====== 顶点 stride ====== */
    uint32_t vertexStride; /* MTLVertexDescriptor.layouts[0].stride */
} ShaderMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _GnxShaderStage_MIN GnxShaderStage_GnxShaderStage_Vertex
#define _GnxShaderStage_MAX GnxShaderStage_GnxShaderStage_Mesh
#define _GnxShaderStage_ARRAYSIZE ((GnxShaderStage)(GnxShaderStage_GnxShaderStage_Mesh+1))

#define _GnxShaderFormat_MIN GnxShaderFormat_GnxShaderFormat_SPIRV
#define _GnxShaderFormat_MAX GnxShaderFormat_GnxShaderFormat_GLSL
#define _GnxShaderFormat_ARRAYSIZE ((GnxShaderFormat)(GnxShaderFormat_GnxShaderFormat_GLSL+1))

#define UniformMemberMessage_format_ENUMTYPE VertexDataFormat




#define VertexInputMessage_format_ENUMTYPE VertexDataFormat

#define ShaderMessage_shaderStage_ENUMTYPE GnxShaderStage
#define ShaderMessage_shaderFormat_ENUMTYPE GnxShaderFormat


/* Initializer values for message structs */
#define UniformMemberMessage_init_default        {{{NULL}, NULL}, 0, 0, _VertexDataFormat_MIN}
#define UniformBufferLayoutMessage_init_default  {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define PushConstantMessage_init_default         {{{NULL}, NULL}, 0, 0, 0}
#define ShaderResourceMessage_init_default       {{{NULL}, NULL}, 0, 0, 0, 0}
#define VertexInputMessage_init_default          {{{NULL}, NULL}, 0, _VertexDataFormat_MIN, 0}
#define ShaderMessage_init_default               {_GnxShaderStage_MIN, _GnxShaderFormat_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}
#define UniformMemberMessage_init_zero           {{{NULL}, NULL}, 0, 0, _VertexDataFormat_MIN}
#define UniformBufferLayoutMessage_init_zero     {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define PushConstantMessage_init_zero            {{{NULL}, NULL}, 0, 0, 0}
#define ShaderResourceMessage_init_zero          {{{NULL}, NULL}, 0, 0, 0, 0}
#define VertexInputMessage_init_zero             {{{NULL}, NULL}, 0, _VertexDataFormat_MIN, 0}
#define ShaderMessage_init_zero                  {_GnxShaderStage_MIN, _GnxShaderFormat_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define UniformMemberMessage_name_tag            1
#define UniformMemberMessage_offset_tag          2
#define UniformMemberMessage_size_tag            3
#define UniformMemberMessage_format_tag          4
#define UniformBufferLayoutMessage_name_tag      1
#define UniformBufferLayoutMessage_dataSize_tag  2
#define UniformBufferLayoutMessage_set_tag       3
#define UniformBufferLayoutMessage_binding_tag   4
#define UniformBufferLayoutMessage_members_tag   5
#define PushConstantMessage_name_tag             1
#define PushConstantMessage_size_tag             2
#define PushConstantMessage_set_tag              3
#define PushConstantMessage_binding_tag          4
#define ShaderResourceMessage_name_tag           1
#define ShaderResourceMessage_set_tag            2
#define ShaderResourceMessage_binding_tag        3
#define ShaderResourceMessage_msl_texture_tag    4
#define ShaderResourceMessage_msl_sampler_tag    5
#define VertexInputMessage_semantic_tag          1
#define VertexInputMessage_location_tag          2
#define VertexInputMessage_format_tag            3
#define VertexInputMessage_offset_tag            4
#define ShaderMessage_shaderStage_tag            1
#define ShaderMessage_shaderFormat_tag           2
#define ShaderMessage_entryPoint_tag             3
#define ShaderMessage_sourceHash_tag             4
#define ShaderMessage_compiledShader_tag         5
#define ShaderMessage_uniformBuffers_tag         6
#define ShaderMessage_pushConstants_tag          7
#define ShaderMessage_resources_tag              8
#define ShaderMessage_vertexInputs_tag           9
#define ShaderMessage_threadgroupSizeX_tag       10
#define ShaderMessage_threadgroupSizeY_tag       11
#define ShaderMessage_threadgroupSizeZ_tag       12
#define ShaderMessage_vertexStride_tag           13

/* Struct field encoding specification for nanopb */
#define UniformMemberMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            2) \
X(a, STATIC,   SINGULAR, UINT32,   size,              3) \
X(a, STATIC,   SINGULAR, UENUM,    format,            4)
#define UniformMemberMessage_CALLBACK pb_default_field_callback
#define UniformMemberMessage_DEFAULT NULL

#define UniformBufferLayoutMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   dataSize,          2) \
X(a, STATIC,   SINGULAR, UINT32,   set,               3) \
X(a, STATIC,   SINGULAR, UINT32,   binding,           4) \
X(a, CALLBACK, REPEATED, MESSAGE,  members,           5)
#define UniformBufferLayoutMessage_CALLBACK pb_default_field_callback
#define UniformBufferLayoutMessage_DEFAULT NULL
#define UniformBufferLayoutMessage_members_MSGTYPE UniformMemberMessage

#define PushConstantMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   size,              2) \
X(a, STATIC,   SINGULAR, UINT32,   set,               3) \
X(a, STATIC,   SINGULAR, UINT32,   binding,           4)
#define PushConstantMessage_CALLBACK pb_default_field_callback
#define PushConstantMessage_DEFAULT NULL

#define ShaderResourceMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   set,               2) \
X(a, STATIC,   SINGULAR, UINT32,   binding,           3) \
X(a, STATIC,   SINGULAR, UINT32,   msl_texture,       4) \
X(a, STATIC,   SINGULAR, UINT32,   msl_sampler,       5)
#define ShaderResourceMessage_CALLBACK pb_default_field_callback
#define ShaderResourceMessage_DEFAULT NULL

#define VertexInputMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   semantic,          1) \
X(a, STATIC,   SINGULAR, UINT32,   location,          2) \
X(a, STATIC,   SINGULAR, UENUM,    format,            3) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            4)
#define VertexInputMessage_CALLBACK pb_default_field_callback
#define VertexInputMessage_DEFAULT NULL

#define ShaderMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    shaderStage,       1) \
X(a, STATIC,   SINGULAR, UENUM,    shaderFormat,      2) \
X(a, CALLBACK, SINGULAR, STRING,   entryPoint,        3) \
X(a, STATIC,   SINGULAR, UINT64,   sourceHash,        4) \
X(a, CALLBACK, SINGULAR, BYTES,    compiledShader,    5) \
X(a, CALLBACK, REPEATED, MESSAGE,  uniformBuffers,    6) \
X(a, CALLBACK, REPEATED, MESSAGE,  pushConstants,     7) \
X(a, CALLBACK, REPEATED, MESSAGE,  resources,         8) \
X(a, CALLBACK, REPEATED, MESSAGE,  vertexInputs,      9) \
X(a, STATIC,   SINGULAR, UINT32,   threadgroupSizeX,  10) \
X(a, STATIC,   SINGULAR, UINT32,   threadgroupSizeY,  11) \
X(a, STATIC,   SINGULAR, UINT32,   threadgroupSizeZ,  12) \
X(a, STATIC,   SINGULAR, UINT32,   vertexStride,     13)
#define ShaderMessage_CALLBACK pb_default_field_callback
#define ShaderMessage_DEFAULT NULL
#define ShaderMessage_uniformBuffers_MSGTYPE UniformBufferLayoutMessage
#define ShaderMessage_pushConstants_MSGTYPE PushConstantMessage
#define ShaderMessage_resources_MSGTYPE ShaderResourceMessage
#define ShaderMessage_vertexInputs_MSGTYPE VertexInputMessage

extern const pb_msgdesc_t UniformMemberMessage_msg;
extern const pb_msgdesc_t UniformBufferLayoutMessage_msg;
extern const pb_msgdesc_t PushConstantMessage_msg;
extern const pb_msgdesc_t ShaderResourceMessage_msg;
extern const pb_msgdesc_t VertexInputMessage_msg;
extern const pb_msgdesc_t ShaderMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UniformMemberMessage_fields &UniformMemberMessage_msg
#define UniformBufferLayoutMessage_fields &UniformBufferLayoutMessage_msg
#define PushConstantMessage_fields &PushConstantMessage_msg
#define ShaderResourceMessage_fields &ShaderResourceMessage_msg
#define VertexInputMessage_fields &VertexInputMessage_msg
#define ShaderMessage_fields &ShaderMessage_msg

/* Maximum encoded size of messages (where known) */
/* UniformMemberMessage_size depends on runtime parameters */
/* UniformBufferLayoutMessage_size depends on runtime parameters */
/* PushConstantMessage_size depends on runtime parameters */
/* ShaderResourceMessage_size depends on runtime parameters */
/* VertexInputMessage_size depends on runtime parameters */
/* ShaderMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
