/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TEXTUREMESSAGE_PB_H_INCLUDED
#define PB_TEXTUREMESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SamplerMessage_FilterMode {
    SamplerMessage_FilterMode_NEAREST = 0,
    SamplerMessage_FilterMode_LINEAR = 1,
    SamplerMessage_FilterMode_NEAREST_MIPMAP_NEAREST = 2,
    SamplerMessage_FilterMode_NEAREST_MIPMAP_LINEAR = 3,
    SamplerMessage_FilterMode_LINEAR_MIPMAP_NEAREST = 4,
    SamplerMessage_FilterMode_LINEAR_MIPMAP_LINEAR = 5
} SamplerMessage_FilterMode;

typedef enum _SamplerMessage_WrapMode {
    SamplerMessage_WrapMode_REPEAT = 0,
    SamplerMessage_WrapMode_CLAMP = 1,
    SamplerMessage_WrapMode_MIRROR = 2,
    SamplerMessage_WrapMode_CLAMP_TO_EDGE = 3
} SamplerMessage_WrapMode;

/* Struct definitions */
/* ==================== 采样器 ==================== */
typedef struct _SamplerMessage {
    SamplerMessage_FilterMode minFilter;
    SamplerMessage_FilterMode magFilter;
    SamplerMessage_WrapMode wrapS;
    SamplerMessage_WrapMode wrapT;
    float anisotropy;
    float minLOD;
    float maxLOD;
    float lodBias;
} SamplerMessage;

/* ==================== 纹理消息 ==================== */
typedef struct _TextureMessage {
    pb_callback_t imageData;
} TextureMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SamplerMessage_FilterMode_MIN SamplerMessage_FilterMode_NEAREST
#define _SamplerMessage_FilterMode_MAX SamplerMessage_FilterMode_LINEAR_MIPMAP_LINEAR
#define _SamplerMessage_FilterMode_ARRAYSIZE ((SamplerMessage_FilterMode)(SamplerMessage_FilterMode_LINEAR_MIPMAP_LINEAR+1))

#define _SamplerMessage_WrapMode_MIN SamplerMessage_WrapMode_REPEAT
#define _SamplerMessage_WrapMode_MAX SamplerMessage_WrapMode_CLAMP_TO_EDGE
#define _SamplerMessage_WrapMode_ARRAYSIZE ((SamplerMessage_WrapMode)(SamplerMessage_WrapMode_CLAMP_TO_EDGE+1))

#define SamplerMessage_minFilter_ENUMTYPE SamplerMessage_FilterMode
#define SamplerMessage_magFilter_ENUMTYPE SamplerMessage_FilterMode
#define SamplerMessage_wrapS_ENUMTYPE SamplerMessage_WrapMode
#define SamplerMessage_wrapT_ENUMTYPE SamplerMessage_WrapMode



/* Initializer values for message structs */
#define SamplerMessage_init_default              {_SamplerMessage_FilterMode_MIN, _SamplerMessage_FilterMode_MIN, _SamplerMessage_WrapMode_MIN, _SamplerMessage_WrapMode_MIN, 0, 0, 0, 0}
#define TextureMessage_init_default              {{{NULL}, NULL}}
#define SamplerMessage_init_zero                 {_SamplerMessage_FilterMode_MIN, _SamplerMessage_FilterMode_MIN, _SamplerMessage_WrapMode_MIN, _SamplerMessage_WrapMode_MIN, 0, 0, 0, 0}
#define TextureMessage_init_zero                 {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SamplerMessage_minFilter_tag             1
#define SamplerMessage_magFilter_tag             2
#define SamplerMessage_wrapS_tag                 4
#define SamplerMessage_wrapT_tag                 5
#define SamplerMessage_anisotropy_tag            7
#define SamplerMessage_minLOD_tag                8
#define SamplerMessage_maxLOD_tag                9
#define SamplerMessage_lodBias_tag               10
#define TextureMessage_imageData_tag             1

/* Struct field encoding specification for nanopb */
#define SamplerMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    minFilter,         1) \
X(a, STATIC,   SINGULAR, UENUM,    magFilter,         2) \
X(a, STATIC,   SINGULAR, UENUM,    wrapS,             4) \
X(a, STATIC,   SINGULAR, UENUM,    wrapT,             5) \
X(a, STATIC,   SINGULAR, FLOAT,    anisotropy,        7) \
X(a, STATIC,   SINGULAR, FLOAT,    minLOD,            8) \
X(a, STATIC,   SINGULAR, FLOAT,    maxLOD,            9) \
X(a, STATIC,   SINGULAR, FLOAT,    lodBias,          10)
#define SamplerMessage_CALLBACK NULL
#define SamplerMessage_DEFAULT NULL

#define TextureMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    imageData,         1)
#define TextureMessage_CALLBACK pb_default_field_callback
#define TextureMessage_DEFAULT NULL

extern const pb_msgdesc_t SamplerMessage_msg;
extern const pb_msgdesc_t TextureMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SamplerMessage_fields &SamplerMessage_msg
#define TextureMessage_fields &TextureMessage_msg

/* Maximum encoded size of messages (where known) */
/* TextureMessage_size depends on runtime parameters */
#define SamplerMessage_size                      28
#define TEXTUREMESSAGE_PB_H_MAX_SIZE             SamplerMessage_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
