/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "MeshMessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SubMeshMessage, SubMeshMessage, AUTO)


PB_BIND(VertexChannelMessage, VertexChannelMessage, AUTO)


PB_BIND(MeshMessage, MeshMessage, AUTO)



