/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ShaderMessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UniformMemberMessage, UniformMemberMessage, AUTO)


PB_BIND(UniformBufferLayoutMessage, UniformBufferLayoutMessage, AUTO)


PB_BIND(PushConstantMessage, PushConstantMessage, AUTO)


PB_BIND(ShaderResourceMessage, ShaderResourceMessage, AUTO)


PB_BIND(VertexInputMessage, VertexInputMessage, AUTO)


PB_BIND(ShaderMessage, ShaderMessage, AUTO)


PB_BIND(ShaderPackageMessage, ShaderPackageMessage, AUTO)







