/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_COMMON_PB_H_INCLUDED
#define PB_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 索引类型 */
typedef enum _IndiceType {
    IndiceType_UnsignedShort = 0,
    IndiceType_UnsignedInt = 1
} IndiceType;

/* 图元类型 */
typedef enum _PrimitiveMode {
    PrimitiveMode_PrimitiveMode_POINTS = 0,
    PrimitiveMode_PrimitiveMode_LINES = 1,
    PrimitiveMode_PrimitiveMode_LINE_STRIP = 2,
    PrimitiveMode_PrimitiveMode_TRIANGLES = 3,
    PrimitiveMode_PrimitiveMode_TRIANGLE_STRIP = 4
} PrimitiveMode;

/* 顶点通道，也就是顶点属性 */
typedef enum _VertexChannel {
    VertexChannel_kVertexChannelPosition = 0, /* position (vector3) */
    VertexChannel_kVertexChannelNormal = 1, /* Normal (vector3) */
    VertexChannel_kVertexChannelColor = 2, /* Vertex color */
    VertexChannel_kVertexChannelTexCoord0 = 3, /* UV set 0 (vector2) */
    VertexChannel_kVertexChannelTexCoord1 = 4, /* UV set 1 (vector2) */
    VertexChannel_kVertexChannelTangent = 5, /* Tangent (vector4) */
    VertexChannel_kVertexChannelBoneIndex = 6, /* BoneIndex (vec4ui) */
    VertexChannel_kVertexChannelWeight = 7, /* Weight (vector4) */
    VertexChannel_kVertexChannelCount = 8 /* Keep this last! */
} VertexChannel;

/* 顶点格式 */
typedef enum _VertexFormat {
    VertexFormat_VertexFormatInvalid = 0,
    VertexFormat_VertexFormatUChar = 1,
    VertexFormat_VertexFormatUChar2 = 2,
    VertexFormat_VertexFormatUChar3 = 3,
    VertexFormat_VertexFormatUChar4 = 4,
    VertexFormat_VertexFormatChar = 5,
    VertexFormat_VertexFormatChar2 = 6,
    VertexFormat_VertexFormatChar3 = 7,
    VertexFormat_VertexFormatChar4 = 8,
    VertexFormat_VertexFormatUShort = 9,
    VertexFormat_VertexFormatUShort2 = 10,
    VertexFormat_VertexFormatUShort3 = 11,
    VertexFormat_VertexFormatUShort4 = 12,
    VertexFormat_VertexFormatShort = 13,
    VertexFormat_VertexFormatShort2 = 14,
    VertexFormat_VertexFormatShort3 = 15,
    VertexFormat_VertexFormatShort4 = 16,
    VertexFormat_VertexFormatFloat = 28,
    VertexFormat_VertexFormatFloat2 = 29,
    VertexFormat_VertexFormatFloat3 = 30,
    VertexFormat_VertexFormatFloat4 = 31,
    VertexFormat_VertexFormatInt = 32,
    VertexFormat_VertexFormatInt2 = 33,
    VertexFormat_VertexFormatInt3 = 34,
    VertexFormat_VertexFormatInt4 = 35,
    VertexFormat_VertexFormatUInt = 36,
    VertexFormat_VertexFormatUInt2 = 37,
    VertexFormat_VertexFormatUInt3 = 38,
    VertexFormat_VertexFormatUInt4 = 39,
    VertexFormat_VertexFormatHalfFloat = 40,
    VertexFormat_VertexFormatHalfFloat2 = 41,
    VertexFormat_VertexFormatHalfFloat3 = 42,
    VertexFormat_VertexFormatHalfFloat4 = 43
} VertexFormat;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _IndiceType_MIN IndiceType_UnsignedShort
#define _IndiceType_MAX IndiceType_UnsignedInt
#define _IndiceType_ARRAYSIZE ((IndiceType)(IndiceType_UnsignedInt+1))

#define _PrimitiveMode_MIN PrimitiveMode_PrimitiveMode_POINTS
#define _PrimitiveMode_MAX PrimitiveMode_PrimitiveMode_TRIANGLE_STRIP
#define _PrimitiveMode_ARRAYSIZE ((PrimitiveMode)(PrimitiveMode_PrimitiveMode_TRIANGLE_STRIP+1))

#define _VertexChannel_MIN VertexChannel_kVertexChannelPosition
#define _VertexChannel_MAX VertexChannel_kVertexChannelCount
#define _VertexChannel_ARRAYSIZE ((VertexChannel)(VertexChannel_kVertexChannelCount+1))

#define _VertexFormat_MIN VertexFormat_VertexFormatInvalid
#define _VertexFormat_MAX VertexFormat_VertexFormatHalfFloat4
#define _VertexFormat_ARRAYSIZE ((VertexFormat)(VertexFormat_VertexFormatHalfFloat4+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
