/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_COMMON_PB_H_INCLUDED
#define PB_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 索引类型 */
typedef enum _IndiceType {
    IndiceType_UnsignedShort = 0,
    IndiceType_UnsignedInt = 1
} IndiceType;

/* 图元类型 */
typedef enum _PrimitiveType {
    PrimitiveType_PrimitiveType_POINTS = 0,
    PrimitiveType_PrimitiveType_LINES = 1,
    PrimitiveType_PrimitiveType_LINE_STRIP = 2,
    PrimitiveType_PrimitiveType_TRIANGLES = 3,
    PrimitiveType_PrimitiveType_TRIANGLE_STRIP = 4
} PrimitiveType;

/* 顶点通道，也就是顶点属性 */
typedef enum _VertexChannel {
    VertexChannel_VertexChannelPosition = 0, /* position (vector3) */
    VertexChannel_VertexChannelNormal = 1, /* Normal (vector3) */
    VertexChannel_VertexChannelColor = 2, /* Vertex color */
    VertexChannel_VertexChannelTexCoord0 = 3, /* UV set 0 (vector2) */
    VertexChannel_VertexChannelTexCoord1 = 4, /* UV set 1 (vector2) */
    VertexChannel_VertexChannelTangent = 5, /* Tangent (vector4) */
    VertexChannel_VertexChannelBoneIndex = 6, /* BoneIndex (vec4ui) */
    VertexChannel_VertexChannelWeight = 7, /* Weight (vector4) */
    VertexChannel_VertexChannelCount = 8 /* Keep this last! */
} VertexChannel;

/* 顶点格式 */
typedef enum _VertexDataFormat {
    VertexDataFormat_VertexDataFormatInvalid = 0,
    VertexDataFormat_VertexDataFormatUChar = 1,
    VertexDataFormat_VertexDataFormatUChar2 = 2,
    VertexDataFormat_VertexDataFormatUChar3 = 3,
    VertexDataFormat_VertexDataFormatUChar4 = 4,
    VertexDataFormat_VertexDataFormatChar = 5,
    VertexDataFormat_VertexDataFormatChar2 = 6,
    VertexDataFormat_VertexDataFormatChar3 = 7,
    VertexDataFormat_VertexDataFormatChar4 = 8,
    VertexDataFormat_VertexDataFormatUShort = 9,
    VertexDataFormat_VertexDataFormatUShort2 = 10,
    VertexDataFormat_VertexDataFormatUShort3 = 11,
    VertexDataFormat_VertexDataFormatUShort4 = 12,
    VertexDataFormat_VertexDataFormatShort = 13,
    VertexDataFormat_VertexDataFormatShort2 = 14,
    VertexDataFormat_VertexDataFormatShort3 = 15,
    VertexDataFormat_VertexDataFormatShort4 = 16,
    VertexDataFormat_VertexDataFormatFloat = 28,
    VertexDataFormat_VertexDataFormatFloat2 = 29,
    VertexDataFormat_VertexDataFormatFloat3 = 30,
    VertexDataFormat_VertexDataFormatFloat4 = 31,
    VertexDataFormat_VertexDataFormatInt = 32,
    VertexDataFormat_VertexDataFormatInt2 = 33,
    VertexDataFormat_VertexDataFormatInt3 = 34,
    VertexDataFormat_VertexDataFormatInt4 = 35,
    VertexDataFormat_VertexDataFormatUInt = 36,
    VertexDataFormat_VertexDataFormatUInt2 = 37,
    VertexDataFormat_VertexDataFormatUInt3 = 38,
    VertexDataFormat_VertexDataFormatUInt4 = 39,
    VertexDataFormat_VertexDataFormatHalfFloat = 40,
    VertexDataFormat_VertexDataFormatHalfFloat2 = 41,
    VertexDataFormat_VertexDataFormatHalfFloat3 = 42,
    VertexDataFormat_VertexDataFormatHalfFloat4 = 43
} VertexDataFormat;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _IndiceType_MIN IndiceType_UnsignedShort
#define _IndiceType_MAX IndiceType_UnsignedInt
#define _IndiceType_ARRAYSIZE ((IndiceType)(IndiceType_UnsignedInt+1))

#define _PrimitiveType_MIN PrimitiveType_PrimitiveType_POINTS
#define _PrimitiveType_MAX PrimitiveType_PrimitiveType_TRIANGLE_STRIP
#define _PrimitiveType_ARRAYSIZE ((PrimitiveType)(PrimitiveType_PrimitiveType_TRIANGLE_STRIP+1))

#define _VertexChannel_MIN VertexChannel_VertexChannelPosition
#define _VertexChannel_MAX VertexChannel_VertexChannelCount
#define _VertexChannel_ARRAYSIZE ((VertexChannel)(VertexChannel_VertexChannelCount+1))

#define _VertexDataFormat_MIN VertexDataFormat_VertexDataFormatInvalid
#define _VertexDataFormat_MAX VertexDataFormat_VertexDataFormatHalfFloat4
#define _VertexDataFormat_ARRAYSIZE ((VertexDataFormat)(VertexDataFormat_VertexDataFormatHalfFloat4+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
