/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_MESHMESSAGE_PB_H_INCLUDED
#define PB_MESHMESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* 每一个子网格的信息 */
typedef struct _SubMeshInfo {
    uint32_t firstIndex; /* 第一个绘制的索引，即索引个数的偏移 */
    uint32_t indexCount; /* 索引的个数，即绘制顶点的个数 */
    PrimitiveMode topology;
    uint32_t vertexCount; /* 顶点的个数 */
} SubMeshInfo;

/* 顶点通道信息 */
typedef struct _VertexChannelInfo {
    uint32_t offset;
    uint32_t stride;
    VertexFormat format;
    VertexChannel vertexChannel; /* 是什么通道 */
} VertexChannelInfo;

/* mesh的格式定义 */
typedef struct _Mesh {
    pb_callback_t vertexData; /* 顶点数据 */
    pb_callback_t indiceData; /* 索引数据 */
    IndiceType indiceType;
    uint32_t vertexCount; /* 顶点个数 */
    uint32_t indiceCount; /* 索引个数 */
    uint32_t vertexSize; /* 每一个顶点占用的字节大小 */
    pb_callback_t subMeshInfos;
    pb_callback_t vertexChannelInfos;
} Mesh;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SubMeshInfo_init_default                 {0, 0, _PrimitiveMode_MIN, 0}
#define VertexChannelInfo_init_default           {0, 0, _VertexFormat_MIN, _VertexChannel_MIN}
#define Mesh_init_default                        {{{NULL}, NULL}, {{NULL}, NULL}, _IndiceType_MIN, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define SubMeshInfo_init_zero                    {0, 0, _PrimitiveMode_MIN, 0}
#define VertexChannelInfo_init_zero              {0, 0, _VertexFormat_MIN, _VertexChannel_MIN}
#define Mesh_init_zero                           {{{NULL}, NULL}, {{NULL}, NULL}, _IndiceType_MIN, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SubMeshInfo_firstIndex_tag               1
#define SubMeshInfo_indexCount_tag               2
#define SubMeshInfo_topology_tag                 3
#define SubMeshInfo_vertexCount_tag              4
#define VertexChannelInfo_offset_tag             1
#define VertexChannelInfo_stride_tag             2
#define VertexChannelInfo_format_tag             3
#define VertexChannelInfo_vertexChannel_tag      4
#define Mesh_vertexData_tag                      1
#define Mesh_indiceData_tag                      2
#define Mesh_indiceType_tag                      3
#define Mesh_vertexCount_tag                     4
#define Mesh_indiceCount_tag                     5
#define Mesh_vertexSize_tag                      6
#define Mesh_subMeshInfos_tag                    7
#define Mesh_vertexChannelInfos_tag              8

/* Struct field encoding specification for nanopb */
#define SubMeshInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   firstIndex,        1) \
X(a, STATIC,   SINGULAR, UINT32,   indexCount,        2) \
X(a, STATIC,   SINGULAR, UENUM,    topology,          3) \
X(a, STATIC,   SINGULAR, UINT32,   vertexCount,       4)
#define SubMeshInfo_CALLBACK NULL
#define SubMeshInfo_DEFAULT NULL

#define VertexChannelInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, STATIC,   SINGULAR, UINT32,   stride,            2) \
X(a, STATIC,   SINGULAR, UENUM,    format,            3) \
X(a, STATIC,   SINGULAR, UENUM,    vertexChannel,     4)
#define VertexChannelInfo_CALLBACK NULL
#define VertexChannelInfo_DEFAULT NULL

#define Mesh_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    vertexData,        1) \
X(a, CALLBACK, SINGULAR, BYTES,    indiceData,        2) \
X(a, STATIC,   SINGULAR, UENUM,    indiceType,        3) \
X(a, STATIC,   SINGULAR, UINT32,   vertexCount,       4) \
X(a, STATIC,   SINGULAR, UINT32,   indiceCount,       5) \
X(a, STATIC,   SINGULAR, UINT32,   vertexSize,        6) \
X(a, CALLBACK, REPEATED, MESSAGE,  subMeshInfos,      7) \
X(a, CALLBACK, REPEATED, MESSAGE,  vertexChannelInfos,   8)
#define Mesh_CALLBACK pb_default_field_callback
#define Mesh_DEFAULT NULL
#define Mesh_subMeshInfos_MSGTYPE SubMeshInfo
#define Mesh_vertexChannelInfos_MSGTYPE VertexChannelInfo

extern const pb_msgdesc_t SubMeshInfo_msg;
extern const pb_msgdesc_t VertexChannelInfo_msg;
extern const pb_msgdesc_t Mesh_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SubMeshInfo_fields &SubMeshInfo_msg
#define VertexChannelInfo_fields &VertexChannelInfo_msg
#define Mesh_fields &Mesh_msg

/* Maximum encoded size of messages (where known) */
/* Mesh_size depends on runtime parameters */
#define MESHMESSAGE_PB_H_MAX_SIZE                SubMeshInfo_size
#define SubMeshInfo_size                         20
#define VertexChannelInfo_size                   16

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
