/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_TEXTUREMESSAGE_PB_H_INCLUDED
#define PB_TEXTUREMESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 纹理的类型 */
typedef enum _TextureType {
    TextureType_Default = 0,
    TextureType_Normal = 1
} TextureType;

/* Struct definitions */
/* 采样器 */
typedef struct _SamplerMessage {
    char dummy_field;
} SamplerMessage;

/* 纹理的message */
typedef struct _TextureMessage {
    CompressType compressType;
    TextureType textureType;
    bool has_sampler;
    SamplerMessage sampler;
    pb_callback_t imageData;
} TextureMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _TextureType_MIN TextureType_Default
#define _TextureType_MAX TextureType_Normal
#define _TextureType_ARRAYSIZE ((TextureType)(TextureType_Normal+1))


#define TextureMessage_compressType_ENUMTYPE CompressType
#define TextureMessage_textureType_ENUMTYPE TextureType


/* Initializer values for message structs */
#define SamplerMessage_init_default              {0}
#define TextureMessage_init_default              {_CompressType_MIN, _TextureType_MIN, false, SamplerMessage_init_default, {{NULL}, NULL}}
#define SamplerMessage_init_zero                 {0}
#define TextureMessage_init_zero                 {_CompressType_MIN, _TextureType_MIN, false, SamplerMessage_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define TextureMessage_compressType_tag          1
#define TextureMessage_textureType_tag           2
#define TextureMessage_sampler_tag               3
#define TextureMessage_imageData_tag             4

/* Struct field encoding specification for nanopb */
#define SamplerMessage_FIELDLIST(X, a) \

#define SamplerMessage_CALLBACK NULL
#define SamplerMessage_DEFAULT NULL

#define TextureMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    compressType,      1) \
X(a, STATIC,   SINGULAR, UENUM,    textureType,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sampler,           3) \
X(a, CALLBACK, SINGULAR, BYTES,    imageData,         4)
#define TextureMessage_CALLBACK pb_default_field_callback
#define TextureMessage_DEFAULT NULL
#define TextureMessage_sampler_MSGTYPE SamplerMessage

extern const pb_msgdesc_t SamplerMessage_msg;
extern const pb_msgdesc_t TextureMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SamplerMessage_fields &SamplerMessage_msg
#define TextureMessage_fields &TextureMessage_msg

/* Maximum encoded size of messages (where known) */
/* TextureMessage_size depends on runtime parameters */
#define SamplerMessage_size                      0
#define TEXTUREMESSAGE_PB_H_MAX_SIZE             SamplerMessage_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
