/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TEXTUREMESSAGE_PB_H_INCLUDED
#define PB_TEXTUREMESSAGE_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ==================== 纹理类型 ==================== */
typedef enum _TextureType {
    TextureType_Unknown = 0,
    TextureType_Default = 1,
    /* PBR材质贴图 */
    TextureType_Albedo = 2, /* 漫反射/基础色 */
    TextureType_Normal = 3, /* 法线 */
    TextureType_Roughness = 4, /* 粗糙度 */
    TextureType_Metallic = 5, /* 金属度 */
    TextureType_Occlusion = 6, /* AO/环境光遮蔽 */
    TextureType_Emissive = 7, /* 自发光 */
    TextureType_Height = 8, /* 高度/位移 */
    /* 其他 */
    TextureType_Specular = 9,
    TextureType_Detail = 10,
    /* 特殊类型 */
    TextureType_Cubemap = 20,
    TextureType_Lightmap = 21,
    TextureType_Shadowmap = 22,
    TextureType_LookupTable = 23,
    TextureType_Noise = 24,
    TextureType_UI = 25
} TextureType;

/* ==================== 像素格式 ==================== */
typedef enum _PixelFormat {
    PixelFormat_UNKNOWN = 0,
    /* 未压缩格式 */
    PixelFormat_GRAY8 = 1,
    PixelFormat_GRAY8_ALPHA8 = 2,
    PixelFormat_RGB8 = 3,
    PixelFormat_RGBA8 = 4,
    PixelFormat_RGB16F = 5,
    PixelFormat_RGBA16F = 6,
    PixelFormat_RGB32F = 7,
    PixelFormat_RGBA32F = 8,
    PixelFormat_SRGB8 = 9,
    PixelFormat_SRGB8_ALPHA8 = 10,
    /* 压缩格式 */
    PixelFormat_BC1 = 60,
    PixelFormat_BC1_SRGB = 61,
    PixelFormat_BC2 = 62,
    PixelFormat_BC3 = 63,
    PixelFormat_BC3_SRGB = 64,
    PixelFormat_BC4 = 65,
    PixelFormat_BC5 = 66,
    PixelFormat_BC6H = 67,
    PixelFormat_BC7 = 68,
    PixelFormat_BC7_SRGB = 69,
    PixelFormat_ETC2_RGB = 80,
    PixelFormat_ETC2_SRGB = 81,
    PixelFormat_ETC2_RGBA = 82,
    PixelFormat_ASTC_4x4 = 100,
    PixelFormat_ASTC_8x8 = 101,
    /* 其他压缩格式 */
    PixelFormat_PVRTC1_4BPP = 120,
    PixelFormat_PVRTC2_4BPP = 121
} PixelFormat;

typedef enum _SamplerMessage_FilterMode {
    SamplerMessage_FilterMode_NEAREST = 0,
    SamplerMessage_FilterMode_LINEAR = 1,
    SamplerMessage_FilterMode_NEAREST_MIPMAP_NEAREST = 2,
    SamplerMessage_FilterMode_NEAREST_MIPMAP_LINEAR = 3,
    SamplerMessage_FilterMode_LINEAR_MIPMAP_NEAREST = 4,
    SamplerMessage_FilterMode_LINEAR_MIPMAP_LINEAR = 5
} SamplerMessage_FilterMode;

typedef enum _SamplerMessage_WrapMode {
    SamplerMessage_WrapMode_REPEAT = 0,
    SamplerMessage_WrapMode_CLAMP = 1,
    SamplerMessage_WrapMode_MIRROR = 2,
    SamplerMessage_WrapMode_CLAMP_TO_EDGE = 3
} SamplerMessage_WrapMode;

/* Struct definitions */
/* ==================== 采样器 ==================== */
typedef struct _SamplerMessage {
    SamplerMessage_FilterMode minFilter;
    SamplerMessage_FilterMode magFilter;
    SamplerMessage_WrapMode wrapS;
    SamplerMessage_WrapMode wrapT;
    float anisotropy;
    float minLOD;
    float maxLOD;
    float lodBias;
} SamplerMessage;

/* ==================== 纹理消息 ==================== */
typedef struct _TextureMessage {
    /* 基本属性 */
    TextureType textureType;
    CompressType compressType;
    /* 数据信息 */
    bool has_sampler;
    SamplerMessage sampler;
    pb_callback_t imageData;
    /* 尺寸信息 */
    uint32_t width;
    uint32_t height;
    uint32_t depth;
    uint32_t mipLevels;
    uint32_t arrayLayers;
    /* 格式信息 */
    PixelFormat format;
    uint32_t bytesPerPixel;
    /* 布尔属性 */
    bool isSRGB;
    bool hasAlpha;
    bool isCubemap;
    bool isCompressed;
    uint32_t dataSize;
    uint64_t hash;
    /* 源信息（可选） */
    pb_callback_t sourceFile;
    pb_callback_t importTime;
    pb_callback_t engineVersion;
} TextureMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _TextureType_MIN TextureType_Unknown
#define _TextureType_MAX TextureType_UI
#define _TextureType_ARRAYSIZE ((TextureType)(TextureType_UI+1))

#define _PixelFormat_MIN PixelFormat_UNKNOWN
#define _PixelFormat_MAX PixelFormat_PVRTC2_4BPP
#define _PixelFormat_ARRAYSIZE ((PixelFormat)(PixelFormat_PVRTC2_4BPP+1))

#define _SamplerMessage_FilterMode_MIN SamplerMessage_FilterMode_NEAREST
#define _SamplerMessage_FilterMode_MAX SamplerMessage_FilterMode_LINEAR_MIPMAP_LINEAR
#define _SamplerMessage_FilterMode_ARRAYSIZE ((SamplerMessage_FilterMode)(SamplerMessage_FilterMode_LINEAR_MIPMAP_LINEAR+1))

#define _SamplerMessage_WrapMode_MIN SamplerMessage_WrapMode_REPEAT
#define _SamplerMessage_WrapMode_MAX SamplerMessage_WrapMode_CLAMP_TO_EDGE
#define _SamplerMessage_WrapMode_ARRAYSIZE ((SamplerMessage_WrapMode)(SamplerMessage_WrapMode_CLAMP_TO_EDGE+1))

#define SamplerMessage_minFilter_ENUMTYPE SamplerMessage_FilterMode
#define SamplerMessage_magFilter_ENUMTYPE SamplerMessage_FilterMode
#define SamplerMessage_wrapS_ENUMTYPE SamplerMessage_WrapMode
#define SamplerMessage_wrapT_ENUMTYPE SamplerMessage_WrapMode

#define TextureMessage_textureType_ENUMTYPE TextureType
#define TextureMessage_compressType_ENUMTYPE CompressType
#define TextureMessage_format_ENUMTYPE PixelFormat


/* Initializer values for message structs */
#define SamplerMessage_init_default              {_SamplerMessage_FilterMode_MIN, _SamplerMessage_FilterMode_MIN, _SamplerMessage_WrapMode_MIN, _SamplerMessage_WrapMode_MIN, 0, 0, 0, 0}
#define TextureMessage_init_default              {_TextureType_MIN, _CompressType_MIN, false, SamplerMessage_init_default, {{NULL}, NULL}, 0, 0, 0, 0, 0, _PixelFormat_MIN, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SamplerMessage_init_zero                 {_SamplerMessage_FilterMode_MIN, _SamplerMessage_FilterMode_MIN, _SamplerMessage_WrapMode_MIN, _SamplerMessage_WrapMode_MIN, 0, 0, 0, 0}
#define TextureMessage_init_zero                 {_TextureType_MIN, _CompressType_MIN, false, SamplerMessage_init_zero, {{NULL}, NULL}, 0, 0, 0, 0, 0, _PixelFormat_MIN, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SamplerMessage_minFilter_tag             1
#define SamplerMessage_magFilter_tag             2
#define SamplerMessage_wrapS_tag                 4
#define SamplerMessage_wrapT_tag                 5
#define SamplerMessage_anisotropy_tag            7
#define SamplerMessage_minLOD_tag                8
#define SamplerMessage_maxLOD_tag                9
#define SamplerMessage_lodBias_tag               10
#define TextureMessage_textureType_tag           1
#define TextureMessage_compressType_tag          2
#define TextureMessage_sampler_tag               3
#define TextureMessage_imageData_tag             4
#define TextureMessage_width_tag                 5
#define TextureMessage_height_tag                6
#define TextureMessage_depth_tag                 7
#define TextureMessage_mipLevels_tag             8
#define TextureMessage_arrayLayers_tag           9
#define TextureMessage_format_tag                10
#define TextureMessage_bytesPerPixel_tag         11
#define TextureMessage_isSRGB_tag                12
#define TextureMessage_hasAlpha_tag              13
#define TextureMessage_isCubemap_tag             14
#define TextureMessage_isCompressed_tag          15
#define TextureMessage_dataSize_tag              16
#define TextureMessage_hash_tag                  17
#define TextureMessage_sourceFile_tag            18
#define TextureMessage_importTime_tag            19
#define TextureMessage_engineVersion_tag         20

/* Struct field encoding specification for nanopb */
#define SamplerMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    minFilter,         1) \
X(a, STATIC,   SINGULAR, UENUM,    magFilter,         2) \
X(a, STATIC,   SINGULAR, UENUM,    wrapS,             4) \
X(a, STATIC,   SINGULAR, UENUM,    wrapT,             5) \
X(a, STATIC,   SINGULAR, FLOAT,    anisotropy,        7) \
X(a, STATIC,   SINGULAR, FLOAT,    minLOD,            8) \
X(a, STATIC,   SINGULAR, FLOAT,    maxLOD,            9) \
X(a, STATIC,   SINGULAR, FLOAT,    lodBias,          10)
#define SamplerMessage_CALLBACK NULL
#define SamplerMessage_DEFAULT NULL

#define TextureMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    textureType,       1) \
X(a, STATIC,   SINGULAR, UENUM,    compressType,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sampler,           3) \
X(a, CALLBACK, SINGULAR, BYTES,    imageData,         4) \
X(a, STATIC,   SINGULAR, UINT32,   width,             5) \
X(a, STATIC,   SINGULAR, UINT32,   height,            6) \
X(a, STATIC,   SINGULAR, UINT32,   depth,             7) \
X(a, STATIC,   SINGULAR, UINT32,   mipLevels,         8) \
X(a, STATIC,   SINGULAR, UINT32,   arrayLayers,       9) \
X(a, STATIC,   SINGULAR, UENUM,    format,           10) \
X(a, STATIC,   SINGULAR, UINT32,   bytesPerPixel,    11) \
X(a, STATIC,   SINGULAR, BOOL,     isSRGB,           12) \
X(a, STATIC,   SINGULAR, BOOL,     hasAlpha,         13) \
X(a, STATIC,   SINGULAR, BOOL,     isCubemap,        14) \
X(a, STATIC,   SINGULAR, BOOL,     isCompressed,     15) \
X(a, STATIC,   SINGULAR, UINT32,   dataSize,         16) \
X(a, STATIC,   SINGULAR, UINT64,   hash,             17) \
X(a, CALLBACK, SINGULAR, STRING,   sourceFile,       18) \
X(a, CALLBACK, SINGULAR, STRING,   importTime,       19) \
X(a, CALLBACK, SINGULAR, STRING,   engineVersion,    20)
#define TextureMessage_CALLBACK pb_default_field_callback
#define TextureMessage_DEFAULT NULL
#define TextureMessage_sampler_MSGTYPE SamplerMessage

extern const pb_msgdesc_t SamplerMessage_msg;
extern const pb_msgdesc_t TextureMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SamplerMessage_fields &SamplerMessage_msg
#define TextureMessage_fields &TextureMessage_msg

/* Maximum encoded size of messages (where known) */
/* TextureMessage_size depends on runtime parameters */
#define SamplerMessage_size                      28
#define TEXTUREMESSAGE_PB_H_MAX_SIZE             SamplerMessage_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
